C = imread('C1 brain.jpg');
subplot(3,2,1);
imshow(C, []);
title('Original Image');
drawnow;
subplot(3,2,2);
[pixelCounts, grayLevels] = imhist(C, 256);
bar(grayLevels, pixelCounts, 'BarWidth', 1);
lastGL = find(pixelCounts > 0,1, 'last');
xlim([0, lastGL]);
grid on;
ax = gca;
ax.XTick = 0 : 50: lastGL;
title('Histogram of Non-Black pixels');
xlabel('Gray Level');
ylabel('Pixel Counts');
drawnow;
thresholdValue = 55;
binaryImage = C > thresholdValue;
subplot(3,2,3);
imshow(binaryImage, []);
title('Initial binary image at 55 Gray levels');
binaryImage = bwareafilt(binaryImage, 2);
binaryImage = imopen(binaryImage, true(5));
binaryImage = bwareafilt(binaryImage, 1);
binaryImage = imfill(binaryImage, 'holes');
binaryImage = imdilate(binaryImage, true(5));
subplot(3,2,4);
imshow(binaryImage, []);
title('Final Binary Image of Skull Alone');
skullFreeImage = C;
skullFreeImage(~binaryImage) = 0;
subplot(3,2,5);
imshow(skullFreeImage, []);
title('Gray Scale Image with skull extracted');
